### ISSUE TITLE
Please help publish to JCentre

### ISSUE THREAD

**Issue by knservis** [snowplow-incubator/piinguin#13]
Travis cannot sync to maven (error here: https://travis-ci.org/snowplow-incubator/piinguin )

But the artifacts are here https://bintray.com/snowplow/snowplow-maven/piinguin-client#

**Comment by alexanderdean** [comment]
I've sent the message

**Comment by alexanderdean** [comment]
Is this done?

**Comment by knservis** [comment]
yes it is. thank you
