### ISSUE TITLE
Add Bintray credentials to .travis.yml

### ISSUE THREAD

**Issue by knservis** [snowplow-incubator/piinguin#9]
Please fill in:

```
  - secure: BINTRAY_SNOWPLOW_MAVEN_API_KEY
  - secure: BINTRAY_SNOWPLOW_MAVEN_USER
  - secure: SONA_PASS
  - secure: BINTRAY_SNOWPLOW_GENERIC_API_KEY
  - secure: BINTRAY_SNOWPLOW_GENERIC_USER
```

Here: https://github.com/snowplow-incubator/piinguin/blob/initial/.travis.yml#L17-L22

**Comment by alexanderdean** [comment]
I don't understand this - why would you want Maven credentials for publishing a server?

**Comment by knservis** [comment]
This will publish the server and the client on bintray and the client would be also published to maven. I don't know if this is correct. @BenFradet Is that not the right way?

**Comment by BenFradet** [comment]
it is

**Comment by alexanderdean** [comment]
So you need the Bintray generic creds plus the Maven ones? You only mention Maven above.

**Comment by knservis** [comment]
@alexanderdean I did not find that in the example @BenFradet pointed me to (https://github.com/snowplow/scala-maxmind-iplookups/blob/develop/.travis/deploy.sh). I thought that bintray are the only ones needed, but somehow they are credentials that allow a `bintraySyncMavenCentral`. @BenFradet what is missing?

**Comment by BenFradet** [comment]
As I said before:

- if you need to publish a library you can look at https://github.com/snowplow/scala-maxmind-iplookups, the specific issues relating to ci/cd they are snowplow/scala-maxmind-iplookups#54 and snowplow/scala-maxmind-iplookups#51
- for a project that needs to land only in bintray (the snowplow-generic repo), you can look at stream enrich, the specific issue is https://github.com/snowplow/snowplow/issues/3441
- for a project that needs to land in s3, you can look at cc, the specific issue is https://github.com/snowplow/snowplow/issues/3712

Sorry I didn't specify the issues previously.

**Comment by knservis** [comment]
Good chat this morning @BenFradet thanks. Updated with `SONA_PASS` and `SONA_USER`.

**Comment by alexanderdean** [comment]
Will leave the `SONA_USER` for you to add manually.
